name: team_dart_knights_sih
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  amplify_authenticator: ^0.2.2
  date_time_picker: ^2.1.0

  flare_flutter: ^2.0.6
  randomizer: ^0.0.2
  flrx_validator: ^0.4.0+2
  flutter_login: ^4.0.0
  font_awesome_flutter: ^10.1.0
  amazon_cognito_identity_dart_2: ^3.0.0
  fluent_ui: ^3.12.0
  intl: ^0.17.0

  window_manager: ^0.2.5
  system_theme: ^2.0.0
  http: ^0.13.4
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  easy_sidemenu: ^0.3.1
  fluentui_system_icons: ^1.1.176
  data_table_2: ^2.3.5
  equatable: ^2.0.3
  modal_side_sheet: ^0.0.1
  flutter_staggered_animations: ^1.0.0
  table_calendar: ^3.0.6
  aws_cloudsearchdomain_api: ^1.2.0
  flutter_staggered_grid_view: ^0.6.2
  fluttertoast: ^8.0.9
  amplify_flutter: ^0.6.5
  amplify_auth_cognito: ^0.6.5
  amplify_api: ^0.6.5
  file_picker: any
  tflite_flutter: ^0.9.0
  google_ml_kit: ^0.12.0
  camera: ^0.10.0
  lottie: ^1.4.1
  image: ^3.1.3
  bitmap: ^0.1.2
  dotted_border: ^2.0.0+2
  fab_circular_menu: ^1.0.2
  image_picker: ^0.8.5+3
  geolocator: ^9.0.1
  amplify_storage_s3: ^0.6.5 
  modal_bottom_sheet: ^2.1.0
  scidart: ^0.0.2-dev.6
  tflite_flutter_helper: ^0.2.1
  flutter_screenutil: ^5.5.3+2

  get: ^4.6.5
  csv: ^5.0.1
  universal_html: ^2.0.8
  path_provider: ^2.0.11
  file_saver: ^0.1.1
  syncfusion_flutter_charts: ^20.2.44
  internet_connection_checker: ^0.0.1+4
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/
    - assets/models/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
